application:
  name: itemservice
  message: Configured by Local Server
server:
  port: 8083
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://item-microservice-db.mysql.database.azure.com:3306/items #your db URL here, keep /goals
    username: spring #your username here, probably also probably username@dbserver required
    password: admin #your pw here
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
