application:
  name: userservice
  message: Configured by Local Server
server:
  port: 8082
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://user-microservice-db.mysql.database.azure.com:3306/users
    username: spring
    password: UserAdmin123!
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
  #jms:
   # servicebus:
    #  connection-string: Endpoint=sb://goalsservice.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=WSJdd5dkKAAs2SKz6qpaD4WlLbr2ssOpx+ASbP9dDdA=
     # pricing-tier: standard
      #topic-client-id: 6ea22758-6c80-4841-88dc-182bf540d7e0
uuids:
  user-type: 
    volunteer: c1ee82fa-35d6-11ee-b0c3-d65d517f8931
    npo: d0f055d5-35d6-11ee-b0c3-d65d517f8931
    partner: d7755d26-35d6-11ee-b0c3-d65d517f8931
    group: cb7f53c5-35d6-11ee-b0c3-d65d517f8931
